window.CLIENT_CONFIG = {
  clientSlug: 'lean-labs',
  providerName: 'Lean Labs',
  agentEndpoint: '/api/agent',
  notificationEndpoint: '/api/notify',
  platforms: ['hubspot', 'g2', 'google'],
  reviewLinks: {
    hubspot: 'https://ecosystem.hubspot.com/marketplace/solutions/lean-labs',
    g2: 'https://www.g2.com/products/lean-labs/take_survey',
    google: 'https://g.page/lean-labs/review',
  },
  welcomeVideoUrl: 'https://www.leanlabs.com/hubfs/LL%20v5/videos/Reputation%20Rocket%20Intro.mp4',
  welcomeVideoPoster: 'https://www.leanlabs.com/hubfs/LL%20v5/videos/7c248b618a126294316f6a.gif',
  interviewQuestions: [
    'Why did you choose Lean Labs?',
    'What were you hoping to achieve?',
    'How did we deliver on your expectations?',
  ],
  videoCaptureEnabled: true,
  thankYouUrl: 'https://leanlabs.com/reputation-rocket/thank-you',
  thankYouRedirectDelayMs: 50000,
  allowedRedirectHosts: ['leanlabs.com', 'www.leanlabs.com'],
  supportEmail: 'help@leanlabs.com',
  hubspotPortalId: '275827',
  hubspotFormId: '102ade8e-7204-41f9-80a0-6a5808c71089',
  hubspotFormRegion: 'na1',
};