window.CLIENT_CONFIG = {
  clientSlug: 'lean-labs',
  providerName: 'Lean Labs',
  logoFaviconDomain: 'leanlabs.com',
  agentEndpoint: '/api/agent',
  notificationEndpoint: '/api/notify',
  platforms: ['hubspot', 'g2', 'google'],
  reviewLinks: {
    hubspot: 'https://ecosystem.hubspot.com/marketplace/solutions/lean-labs',
    g2: 'https://www.g2.com/products/lean-labs/take_survey',
    google: 'https://g.page/lean-labs/review',
  },
  welcomeVideoUrl: '',
  videoCaptureEnabled: true,
  thankYouUrl: 'https://leanlabs.com/reputation-rocket/thank-you',
  allowedRedirectHosts: ['leanlabs.com', 'www.leanlabs.com'],
  supportEmail: 'help@leanlabs.com',
  hubspotPortalId: '275827',
  hubspotFormId: '102ade8e-7204-41f9-80a0-6a5808c71089',
  hubspotFormRegion: 'na1',
};