window.CLIENT_CONFIG = {
  clientSlug: 'eimmigration',
  providerName: 'eimmigration',
  agentEndpoint: '/api/agent',
  notificationEndpoint: '/api/notify',
  platforms: ['gartner', 'g2', 'trustpilot'],
  reviewLinks: {
    gartner: 'https://www.gartner.com/reviews/product/eimmigration',
    g2: 'https://www.g2.com/products/eimmigration-by-cerenade/reviews/start',
    trustpilot: 'https://www.trustpilot.com/evaluate/cerenade.com',
  },
  welcomeVideoUrl: '/assets/video/Reputation Rocket Intro.mp4',
  welcomeVideoPoster: '/assets/image/7c248b618a126294316f6a.gif',
  interviewQuestions: [
    'Why did you choose eimmigration?',
    'What were you hoping to achieve?',
    'How did we deliver on your expectations?',
  ],
  videoCaptureEnabled: false,
  thankYouUrl: '',
  thankYouRedirectDelayMs: 120000,
  allowedRedirectHosts: ['eimmigration.com', 'www.eimmigration.com', 'get.eimmigration.com'],
  supportEmail: 'edward@lean-labs.com',
  hubspotPortalId: '45248900',
  hubspotFormId: 'd636fadd-2e72-4663-bf26-e465c7d419a5',
  hubspotFormRegion: 'na1',
  hubspotCompleteProperty: 'rr_iscomplete',
  hubspotCompleteValue: 'Yes',
  hubspotOutcomeProperty: 'rr_outcome',
  hubspotOutcomePositiveValue: 'positive',
  hubspotOutcomeNegativeValue: 'negative',
};
